version: "3"

tasks:
  build:
    desc: "Build the project"
    cmds:
      - go build -o ./app/sendmind-hub ./cmd/server

  test:
    desc: "Run tests"
    cmds:
      - go test ./...

  lint:
    desc: "Run golangci-lint to check for linting issues"
    cmds:
      - golangci-lint run ./...
    silent: true

  fix:
    desc: "Run golangci-lint to fix linting issues"
    cmds:
      - golangci-lint run --fix ./...
    silent: true

  run:
    desc: "Run Server"
    cmds:
      - go run ./cmd/server/main.go

  push:
    desc: "Push docker hub"
    cmds:
      - docker build --platform linux/amd64 -t sendmind-hub:latest .
      - docker tag sendmind-hub:latest seninder/sendmind-hub:latest
      - docker push seninder/sendmind-hub:latest
